apiVersion: v1
kind: Service

metadata:
  name: analytics-service
  namespace: enterprise-devops

spec:

  type: LoadBalancer

  selector:

    app: analytics-platform
    version: blue

  ports:

  - port: 80
    targetPort: 8080