apiVersion: v1
kind: ConfigMap

metadata:
  name: analytics-config
  namespace: enterprise-devops

data:
  APP_NAME: "Enterprise Product Deployment Platform"
  APP_ENV: "dev"
  SERVER_PORT: "8081"
  AWS_REGION: "us-west-1"
